### ISSUE TITLE
Why access token is in url but not as query parameter?

### ISSUE THREAD

**Issue by kurochenko** [Ceskasporitelna/WebAPI#13]
When connecting to WebApi i get access token in following URI `redirect#access_token=demo_892cee32aca75496b6e61808215ee2b4&token_type=Bearer&expires_in=3600`. Why do i get it after `#` but not `?`. In this case I have to parse the URI myself instead of using means of framework or any lib.

**Comment by petrdvorak** [comment]
Hello, nice to finally see you here. :) You are using "implicit grant" - hence the URL provided by ČS is correct, see for example here:

https://auth0.com/docs/api-auth/tutorials/implicit-grant (or anywhere else).

Implicit grant is handful for JavaScript only applications. But I believe this is not your case.

What you actually (probably?) need is a "authorization code" grant, that will pass the "code" as query parameter in URL. Then, based on the "code" value, your server will ask for access token using server-server communication. If you need help, I can invite you to our Express Statement repository (Java / Spring), so that you can steal our code... ;-)

**Comment by kurochenko** [comment]
Oh, right, i get it now. Thanks @petrdvorak  :) 

Yeah, i think that inspiration by existing code would make the learning process faster :) thank you for offer.

**Comment by petrdvorak** [comment]
OK, invite sent (read only)...

**Comment by jmachan** [comment]
Thanks @petrdvorak for the provided guidance!
